from . import place
from . import res_partner
from . import brand
from . import contract
from . import tooltip
from . import mfp_data
from . import mfp_record
from . import install_record
from . import alert_record
from . import account_move
